### ISSUE TITLE
Insert interval point

### ISSUE THREAD

**Issue by thorfour** [rdleal/intervalst#2]
I have some intervals that represent a single point (min==max). However the validation check flags the interval as invalid. 

There doesn't seem to be a reason why a point can't exist in the tree, and changing the check to just check for less than instead of lte seems to make it work just fine.

Can this be changed to allow points in the tree?

**Comment by rdleal** [comment]
I think that makes sense, but changing the validation only can cause a break change on other users who can be relying on this rule of the tree not allowing point intervals. I'd rather create a configuration for that, like a new constructor that receives some options:

```go
st := interval.NewSearchTreeWithOptions(cmp, interval.AllowPoint(true)) // cmp function omitted for brevity
```

then in the validation function we check for that configuration field:
```go
func (it interval[V, T]) isInvalid(cmp CmpFunc[T]) bool {
        // assuming allowPoint contains false as default, 
        // but is overwritten by the option passed to the constructor.
        if it.allowPoint {
                return cmp.lt(it.end, it.start)
       }
	return cmp.lte(it.end, it.start)
}
```

This way we keep the current behavior, but allows use cases like yours to configure the tree as needed.

What do you think?

**Comment by thorfour** [comment]
Yes that sounds perfect!

**Comment by thorfour** [comment]
Alternatively we can just expand the current function signature to accept variadic parameters

```go

type Option func(*SearchTree[V,T])

func NewSearchTree[V, T any](cmp CmpFunc[T], options ...Option) *SearchTree[V, T] {
     ...
     t := &SearchTree[V, T]{
		cmp: cmp,
     }
     for _, option := range options {
          option(t)
     }
}
```

**Comment by rdleal** [comment]
Nice. I try to push this change today, at most tomorrow. If you have urgency, you might consider using [this fork](https://github.com/abraithwaite/intervalst) from this project. The owner of the fork probably had the same use case as yours, and just changed the validation function to solve that.

**Comment by rdleal** [comment]
> Alternatively we can just expand the current function signature to accept variadic parameters
> 
> ```go
> type Option func(*SearchTree[V,T])
> 
> func NewSearchTree[V, T any](cmp CmpFunc[T], options ...Option) *SearchTree[V, T] {
>      ...
>      t := &SearchTree[V, T]{
> 		cmp: cmp,
>      }
>      for _, option := range options {
>           option(t)
>      }
> }
> ```

Yes, that's an alternative, but still might cause a break change if someone is relying on the constructor signature, by injecting the constructor for mocking, for example:
```go
type TreeConstructorFunc[T, V any] func(cmp interval.CmpFunc[V]) *interval.SearchTree[T, V]

type TreeBuilder[T, V any] struct {
	newTree TreeConstructorFunc[T, V]
}

func NewTreeBuilder[T, V any](tc TreeConstructorFunc[T, V]) *TreeBuilder[T, V] {
	return &TreeBuilder[T, V]{
		newTree: tc,
	}
}
```
On the production code:
```go
func main() {
        tb := NewTreeBuilder(interval.NewSearchTree[string, int])
}
```
On the test:
```go
func mockConstructor[V, T any](cmp interval.CmpFunc[V]) *interval.SearchTree[T, V] {
	// return some pre-configured tree for testing
}

func TestTreeBuilder_SomeMethod() {

	bt := NewTreeBuilder(mockConstructor[string, int])

        // test SomeMethod ...
}
```

Even though you suggestion is neat, and prettier than what I thought, it has the potential to break code like the above. So as a rule of thumb, I prefer to have an ugly API than a (potentially) broken one. Does that make sense?

**Comment by rdleal** [comment]
@thorfour I've pushed some code to the branch `point-interval`. I still need to add some descriptions to the new public types, but that should be already working. If you want to give it a try:
```sh
go get github.com/rdleal/intervalst@point-interval
```

On your code you can instantiate a tree that accepts point interval like this:
```go
// Replace T by the type of the value you want inside the tree.
st := interval.NewSearchTreeWithOptions[T](cmpFunc, interval.TreeWithPointInterval()) // cmpFunc omitted for brevity
```

Or if you are using a multi value tree:
```go
// Replace T by the type of the value you want inside the tree.
st := interval.NewMultiValueSearchTreeWithOptions[T](cmpFunc, interval.TreeWithPointInterval()) // cmpFunc omitted for brevity
```

**Comment by thorfour** [comment]
Dropped in your branch in my code and it worked great! Thank you so much!

**Comment by rdleal** [comment]
@thorfour glad to hear the changes worked for you!

I've pushed a new tag `v1.2.0`, so you should be good to go with the new official version:
```sh
go get github.com/rdleal/intervalst@v1.2.0
```

Feel free to close this issue if you feel your use case is covered by the package.

Thank you for using it and bringing feedback.

**Comment by thorfour** [comment]
Thanks so much for the quick implementation, worked great!
